# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 08:08
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text="Builds the Article's URL from the title.", max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('image_caption', models.CharField(blank=True, help_text="(Optional) Image's caption.", max_length=100)),
                ('excerpt', models.TextField()),
                ('body', ckeditor.fields.RichTextField()),
                ('publish', models.DateTimeField(auto_now_add=True, verbose_name='Published on')),
                ('guest_author', models.CharField(blank=True, help_text='If the Author is not a registered user, type the name here.', max_length=50, null=True)),
            ],
            options={
                'ordering': ['-publish'],
                'get_latest_by': 'publish',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='post.Tag'),
        ),
    ]
