# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True, help_text="Uncheck this if you don't want the article to appear on the site yet."),
        ),
    ]
