# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20161017_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
